version: 2
jobs:
  build:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/react-mosaic
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
            export PATH="$HOME/.yarn/bin:$PATH"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: mkdir reports
      - run:
          name: Run unit tests
          command: yarn test:unit --reporter mocha-junit-reporter --reporter-options mochaFile=reports/mocha/test-results.xml
      - run:
          name: Lint
          command: yarn test:lint --format junit -o ./reports/tslint/tslint.xml
      - store_test_results:
          path: reports
      - store_artifacts:
          path: ./reports/mocha/test-results.xml
      - store_artifacts:
          path: ./reports/tslint/tslint.xml
